# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: payment-depl
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: payment
#   template:
#     metadata:
#       labels:
#         app: payment
#     spec:
#       containers:
#         - name: payment
#           image: dewanshu96/payment
#           env:
#             - name: JWT_KEY
#               valueFrom:
#                 secretKeyRef:
#                   name: my-secret-new
#                   key: my-secret-new
#             - name: STRIPE_KEY
#               valueFrom:
#                 secretKeyRef:
#                   name: stripe-secret
#                   key: STRIPE_KEY
#             - name: NATS_CLIENT_ID
#               valueFrom:
#                 fieldRef:
#                   fieldPath: metadata.name
#             - name: NATS_URL
#               value: "http://nats-srv:4222"
#             - name: NATS_CLUSTER_ID
#               value: ticketing
#             - name: MONGO_URI
#               value: "mongodb://ticket-mongo-srv:27017/payments"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: payment-srv
# spec:
#   selector:
#     app: payment
#   ports:
#     - port: 3000
#       targetPort: 3000
#       name: payment-port
#       protocol: TCP
